/*
 Navicat Premium Data Transfer

 Source Server         : WTB
 Source Server Type    : MySQL
 Source Server Version : 100225
 Source Host           : 153.92.10.33:3306
 Source Schema         : u6178216_wtb

 Target Server Type    : MySQL
 Target Server Version : 100225
 File Encoding         : 65001

 Date: 12/08/2019 05:54:36
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for tbl_m_catbrand
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_catbrand`;
CREATE TABLE `tbl_m_catbrand`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_admin_seller` int(11) NULL DEFAULT NULL,
  `cat_seller` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `brand_seller` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_catbrand
-- ----------------------------
INSERT INTO `tbl_m_catbrand` VALUES (1, 94, '\'9, 10\'', '\'1, 3\'', '2019-08-11 19:59:46');

-- ----------------------------
-- Table structure for tbl_m_category
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_category`;
CREATE TABLE `tbl_m_category`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name_cat` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_cat` int(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 7 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_category
-- ----------------------------
INSERT INTO `tbl_m_category` VALUES (1, 'Category 03', 1);
INSERT INTO `tbl_m_category` VALUES (2, 'Bujang', 0);
INSERT INTO `tbl_m_category` VALUES (3, 'NULL', 0);
INSERT INTO `tbl_m_category` VALUES (4, 'Category Test', 1);
INSERT INTO `tbl_m_category` VALUES (6, 'Motor 123', 1);

-- ----------------------------
-- Table structure for tbl_m_config
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_config`;
CREATE TABLE `tbl_m_config`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `config_param` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `config_value` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_config
-- ----------------------------
INSERT INTO `tbl_m_config` VALUES (1, 'api_sms_gateway', 'https://api.solusiid.com');
INSERT INTO `tbl_m_config` VALUES (2, 'api_key_sms', '5a36683f9dc56eb9a956f00de887d850');
INSERT INTO `tbl_m_config` VALUES (3, 'pass_sms_gateway', 'asd123');

-- ----------------------------
-- Table structure for tbl_m_grade_admin
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_grade_admin`;
CREATE TABLE `tbl_m_grade_admin`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `grade_code` varchar(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `grade_desc` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `grade_stat` int(1) NULL DEFAULT NULL,
  `access_menu` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_grade_admin
-- ----------------------------
INSERT INTO `tbl_m_grade_admin` VALUES (1, 'ADM', 'Admin', 1, '{\"master\":[{\"menu_name\":\"Main Category\",\"menu_param\":\"1\"},{\"menu_name\":\"Sub Category\",\"menu_param\":\"2\"}],\"account\":[],\"request\":[],\"system\":[]}');
INSERT INTO `tbl_m_grade_admin` VALUES (2, 'ADM1', 'Admin 1', 1, '{\"master\":[],\"account\":[],\"request\":[],\"system\":[]}');

-- ----------------------------
-- Table structure for tbl_m_kota
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_kota`;
CREATE TABLE `tbl_m_kota`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name_kota` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_kota` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9549 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_kota
-- ----------------------------
INSERT INTO `tbl_m_kota` VALUES (1101, 'KABUPATEN SIMEULUE1', 1);
INSERT INTO `tbl_m_kota` VALUES (1102, 'KABUPATEN ACEH SINGKIL', 1);
INSERT INTO `tbl_m_kota` VALUES (1103, 'KABUPATEN ACEH SELATAN', 1);
INSERT INTO `tbl_m_kota` VALUES (1104, 'KABUPATEN ACEH TENGGARA', 1);
INSERT INTO `tbl_m_kota` VALUES (1105, 'KABUPATEN ACEH TIMUR', 1);
INSERT INTO `tbl_m_kota` VALUES (1106, 'KABUPATEN ACEH TENGAH', 1);
INSERT INTO `tbl_m_kota` VALUES (1107, 'KABUPATEN ACEH BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1108, 'KABUPATEN ACEH BESAR', 1);
INSERT INTO `tbl_m_kota` VALUES (1109, 'KABUPATEN PIDIE', 0);
INSERT INTO `tbl_m_kota` VALUES (1110, 'KABUPATEN BIREUEN', 0);
INSERT INTO `tbl_m_kota` VALUES (1111, 'KABUPATEN ACEH UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1112, 'KABUPATEN ACEH BARAT DAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (1113, 'KABUPATEN GAYO LUES', 0);
INSERT INTO `tbl_m_kota` VALUES (1114, 'KABUPATEN ACEH TAMIANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1115, 'KABUPATEN NAGAN RAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (1116, 'KABUPATEN ACEH JAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (1117, 'KABUPATEN BENER MERIAH', 0);
INSERT INTO `tbl_m_kota` VALUES (1118, 'KABUPATEN PIDIE JAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (1171, 'KOTA BANDA ACEH', 0);
INSERT INTO `tbl_m_kota` VALUES (1172, 'KOTA SABANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1173, 'KOTA LANGSA', 0);
INSERT INTO `tbl_m_kota` VALUES (1174, 'KOTA LHOKSEUMAWE', 0);
INSERT INTO `tbl_m_kota` VALUES (1175, 'KOTA SUBULUSSALAM', 0);
INSERT INTO `tbl_m_kota` VALUES (1201, 'KABUPATEN NIAS', 0);
INSERT INTO `tbl_m_kota` VALUES (1202, 'KABUPATEN MANDAILING NATAL', 0);
INSERT INTO `tbl_m_kota` VALUES (1203, 'KABUPATEN TAPANULI SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1204, 'KABUPATEN TAPANULI TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (1205, 'KABUPATEN TAPANULI UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1206, 'KABUPATEN TOBA SAMOSIR', 0);
INSERT INTO `tbl_m_kota` VALUES (1207, 'KABUPATEN LABUHAN BATU', 0);
INSERT INTO `tbl_m_kota` VALUES (1208, 'KABUPATEN ASAHAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1209, 'KABUPATEN SIMALUNGUN', 0);
INSERT INTO `tbl_m_kota` VALUES (1210, 'KABUPATEN DAIRI', 0);
INSERT INTO `tbl_m_kota` VALUES (1211, 'KABUPATEN KARO', 0);
INSERT INTO `tbl_m_kota` VALUES (1212, 'KABUPATEN DELI SERDANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1213, 'KABUPATEN LANGKAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1214, 'KABUPATEN NIAS SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1215, 'KABUPATEN HUMBANG HASUNDUTAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1216, 'KABUPATEN PAKPAK BHARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1217, 'KABUPATEN SAMOSIR', 0);
INSERT INTO `tbl_m_kota` VALUES (1218, 'KABUPATEN SERDANG BEDAGAI', 0);
INSERT INTO `tbl_m_kota` VALUES (1219, 'KABUPATEN BATU BARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1220, 'KABUPATEN PADANG LAWAS UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1221, 'KABUPATEN PADANG LAWAS', 0);
INSERT INTO `tbl_m_kota` VALUES (1222, 'KABUPATEN LABUHAN BATU SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1223, 'KABUPATEN LABUHAN BATU UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1224, 'KABUPATEN NIAS UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1225, 'KABUPATEN NIAS BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1271, 'KOTA SIBOLGA', 0);
INSERT INTO `tbl_m_kota` VALUES (1272, 'KOTA TANJUNG BALAI', 0);
INSERT INTO `tbl_m_kota` VALUES (1273, 'KOTA PEMATANG SIANTAR', 0);
INSERT INTO `tbl_m_kota` VALUES (1274, 'KOTA TEBING TINGGI', 0);
INSERT INTO `tbl_m_kota` VALUES (1275, 'KOTA MEDAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1276, 'KOTA BINJAI', 0);
INSERT INTO `tbl_m_kota` VALUES (1277, 'KOTA PADANGSIDIMPUAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1278, 'KOTA GUNUNGSITOLI', 0);
INSERT INTO `tbl_m_kota` VALUES (1301, 'KABUPATEN KEPULAUAN MENTAWAI', 0);
INSERT INTO `tbl_m_kota` VALUES (1302, 'KABUPATEN PESISIR SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1303, 'KABUPATEN SOLOK', 0);
INSERT INTO `tbl_m_kota` VALUES (1304, 'KABUPATEN SIJUNJUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (1305, 'KABUPATEN TANAH DATAR', 0);
INSERT INTO `tbl_m_kota` VALUES (1306, 'KABUPATEN PADANG PARIAMAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1307, 'KABUPATEN AGAM', 0);
INSERT INTO `tbl_m_kota` VALUES (1308, 'KABUPATEN LIMA PULUH KOTA', 0);
INSERT INTO `tbl_m_kota` VALUES (1309, 'KABUPATEN PASAMAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1310, 'KABUPATEN SOLOK SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1311, 'KABUPATEN DHARMASRAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (1312, 'KABUPATEN PASAMAN BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1371, 'KOTA PADANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1372, 'KOTA SOLOK', 0);
INSERT INTO `tbl_m_kota` VALUES (1373, 'KOTA SAWAH LUNTO', 0);
INSERT INTO `tbl_m_kota` VALUES (1374, 'KOTA PADANG PANJANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1375, 'KOTA BUKITTINGGI', 0);
INSERT INTO `tbl_m_kota` VALUES (1376, 'KOTA PAYAKUMBUH', 0);
INSERT INTO `tbl_m_kota` VALUES (1377, 'KOTA PARIAMAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1401, 'KABUPATEN KUANTAN SINGINGI', 0);
INSERT INTO `tbl_m_kota` VALUES (1402, 'KABUPATEN INDRAGIRI HULU', 0);
INSERT INTO `tbl_m_kota` VALUES (1403, 'KABUPATEN INDRAGIRI HILIR', 0);
INSERT INTO `tbl_m_kota` VALUES (1404, 'KABUPATEN PELALAWAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1405, 'KABUPATEN S I A K', 0);
INSERT INTO `tbl_m_kota` VALUES (1406, 'KABUPATEN KAMPAR', 0);
INSERT INTO `tbl_m_kota` VALUES (1407, 'KABUPATEN ROKAN HULU', 0);
INSERT INTO `tbl_m_kota` VALUES (1408, 'KABUPATEN BENGKALIS', 0);
INSERT INTO `tbl_m_kota` VALUES (1409, 'KABUPATEN ROKAN HILIR', 0);
INSERT INTO `tbl_m_kota` VALUES (1410, 'KABUPATEN KEPULAUAN MERANTI', 0);
INSERT INTO `tbl_m_kota` VALUES (1471, 'KOTA PEKANBARU', 0);
INSERT INTO `tbl_m_kota` VALUES (1473, 'KOTA D U M A I', 0);
INSERT INTO `tbl_m_kota` VALUES (1501, 'KABUPATEN KERINCI', 0);
INSERT INTO `tbl_m_kota` VALUES (1502, 'KABUPATEN MERANGIN', 0);
INSERT INTO `tbl_m_kota` VALUES (1503, 'KABUPATEN SAROLANGUN', 0);
INSERT INTO `tbl_m_kota` VALUES (1504, 'KABUPATEN BATANG HARI', 0);
INSERT INTO `tbl_m_kota` VALUES (1505, 'KABUPATEN MUARO JAMBI', 0);
INSERT INTO `tbl_m_kota` VALUES (1506, 'KABUPATEN TANJUNG JABUNG TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (1507, 'KABUPATEN TANJUNG JABUNG BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1508, 'KABUPATEN TEBO', 0);
INSERT INTO `tbl_m_kota` VALUES (1509, 'KABUPATEN BUNGO', 0);
INSERT INTO `tbl_m_kota` VALUES (1571, 'KOTA JAMBI', 0);
INSERT INTO `tbl_m_kota` VALUES (1572, 'KOTA SUNGAI PENUH', 0);
INSERT INTO `tbl_m_kota` VALUES (1601, 'KABUPATEN OGAN KOMERING ULU', 0);
INSERT INTO `tbl_m_kota` VALUES (1602, 'KABUPATEN OGAN KOMERING ILIR', 0);
INSERT INTO `tbl_m_kota` VALUES (1603, 'KABUPATEN MUARA ENIM', 0);
INSERT INTO `tbl_m_kota` VALUES (1604, 'KABUPATEN LAHAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1605, 'KABUPATEN MUSI RAWAS', 0);
INSERT INTO `tbl_m_kota` VALUES (1606, 'KABUPATEN MUSI BANYUASIN', 0);
INSERT INTO `tbl_m_kota` VALUES (1607, 'KABUPATEN BANYU ASIN', 0);
INSERT INTO `tbl_m_kota` VALUES (1608, 'KABUPATEN OGAN KOMERING ULU SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1609, 'KABUPATEN OGAN KOMERING ULU TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (1610, 'KABUPATEN OGAN ILIR', 0);
INSERT INTO `tbl_m_kota` VALUES (1611, 'KABUPATEN EMPAT LAWANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1612, 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', 0);
INSERT INTO `tbl_m_kota` VALUES (1613, 'KABUPATEN MUSI RAWAS UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1671, 'KOTA PALEMBANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1672, 'KOTA PRABUMULIH', 0);
INSERT INTO `tbl_m_kota` VALUES (1673, 'KOTA PAGAR ALAM', 0);
INSERT INTO `tbl_m_kota` VALUES (1674, 'KOTA LUBUKLINGGAU', 0);
INSERT INTO `tbl_m_kota` VALUES (1701, 'KABUPATEN BENGKULU SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1702, 'KABUPATEN REJANG LEBONG', 0);
INSERT INTO `tbl_m_kota` VALUES (1703, 'KABUPATEN BENGKULU UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1704, 'KABUPATEN KAUR', 0);
INSERT INTO `tbl_m_kota` VALUES (1705, 'KABUPATEN SELUMA', 0);
INSERT INTO `tbl_m_kota` VALUES (1706, 'KABUPATEN MUKOMUKO', 0);
INSERT INTO `tbl_m_kota` VALUES (1707, 'KABUPATEN LEBONG', 0);
INSERT INTO `tbl_m_kota` VALUES (1708, 'KABUPATEN KEPAHIANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1709, 'KABUPATEN BENGKULU TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (1771, 'KOTA BENGKULU', 0);
INSERT INTO `tbl_m_kota` VALUES (1801, 'KABUPATEN LAMPUNG BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1802, 'KABUPATEN TANGGAMUS', 0);
INSERT INTO `tbl_m_kota` VALUES (1803, 'KABUPATEN LAMPUNG SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1804, 'KABUPATEN LAMPUNG TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (1805, 'KABUPATEN LAMPUNG TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (1806, 'KABUPATEN LAMPUNG UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (1807, 'KABUPATEN WAY KANAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1808, 'KABUPATEN TULANGBAWANG', 0);
INSERT INTO `tbl_m_kota` VALUES (1809, 'KABUPATEN PESAWARAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1810, 'KABUPATEN PRINGSEWU', 0);
INSERT INTO `tbl_m_kota` VALUES (1811, 'KABUPATEN MESUJI', 0);
INSERT INTO `tbl_m_kota` VALUES (1812, 'KABUPATEN TULANG BAWANG BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1813, 'KABUPATEN PESISIR BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1871, 'KOTA BANDAR LAMPUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (1872, 'KOTA METRO', 0);
INSERT INTO `tbl_m_kota` VALUES (1901, 'KABUPATEN BANGKA', 0);
INSERT INTO `tbl_m_kota` VALUES (1902, 'KABUPATEN BELITUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (1903, 'KABUPATEN BANGKA BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (1904, 'KABUPATEN BANGKA TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (1905, 'KABUPATEN BANGKA SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (1906, 'KABUPATEN BELITUNG TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (1971, 'KOTA PANGKAL PINANG', 0);
INSERT INTO `tbl_m_kota` VALUES (2101, 'KABUPATEN KARIMUN', 0);
INSERT INTO `tbl_m_kota` VALUES (2102, 'KABUPATEN BINTAN', 0);
INSERT INTO `tbl_m_kota` VALUES (2103, 'KABUPATEN NATUNA', 0);
INSERT INTO `tbl_m_kota` VALUES (2104, 'KABUPATEN LINGGA', 0);
INSERT INTO `tbl_m_kota` VALUES (2105, 'KABUPATEN KEPULAUAN ANAMBAS', 0);
INSERT INTO `tbl_m_kota` VALUES (2171, 'KOTA B A T A M', 0);
INSERT INTO `tbl_m_kota` VALUES (2172, 'KOTA TANJUNG PINANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3101, 'KABUPATEN KEPULAUAN SERIBU', 0);
INSERT INTO `tbl_m_kota` VALUES (3171, 'KOTA JAKARTA SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3172, 'KOTA JAKARTA TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (3173, 'KOTA JAKARTA PUSAT', 0);
INSERT INTO `tbl_m_kota` VALUES (3174, 'KOTA JAKARTA BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (3175, 'KOTA JAKARTA UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (3201, 'KABUPATEN BOGOR', 0);
INSERT INTO `tbl_m_kota` VALUES (3202, 'KABUPATEN SUKABUMI', 0);
INSERT INTO `tbl_m_kota` VALUES (3203, 'KABUPATEN CIANJUR', 0);
INSERT INTO `tbl_m_kota` VALUES (3204, 'KABUPATEN BANDUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (3205, 'KABUPATEN GARUT', 0);
INSERT INTO `tbl_m_kota` VALUES (3206, 'KABUPATEN TASIKMALAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (3207, 'KABUPATEN CIAMIS', 0);
INSERT INTO `tbl_m_kota` VALUES (3208, 'KABUPATEN KUNINGAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3209, 'KABUPATEN CIREBON', 0);
INSERT INTO `tbl_m_kota` VALUES (3210, 'KABUPATEN MAJALENGKA', 0);
INSERT INTO `tbl_m_kota` VALUES (3211, 'KABUPATEN SUMEDANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3212, 'KABUPATEN INDRAMAYU', 0);
INSERT INTO `tbl_m_kota` VALUES (3213, 'KABUPATEN SUBANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3214, 'KABUPATEN PURWAKARTA', 0);
INSERT INTO `tbl_m_kota` VALUES (3215, 'KABUPATEN KARAWANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3216, 'KABUPATEN BEKASI', 0);
INSERT INTO `tbl_m_kota` VALUES (3217, 'KABUPATEN BANDUNG BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (3218, 'KABUPATEN PANGANDARAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3271, 'KOTA BOGOR', 0);
INSERT INTO `tbl_m_kota` VALUES (3272, 'KOTA SUKABUMI', 0);
INSERT INTO `tbl_m_kota` VALUES (3273, 'KOTA BANDUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (3274, 'KOTA CIREBON', 0);
INSERT INTO `tbl_m_kota` VALUES (3275, 'KOTA BEKASI', 0);
INSERT INTO `tbl_m_kota` VALUES (3276, 'KOTA DEPOK', 0);
INSERT INTO `tbl_m_kota` VALUES (3277, 'KOTA CIMAHI', 0);
INSERT INTO `tbl_m_kota` VALUES (3278, 'KOTA TASIKMALAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (3279, 'KOTA BANJAR', 0);
INSERT INTO `tbl_m_kota` VALUES (3301, 'KABUPATEN CILACAP', 0);
INSERT INTO `tbl_m_kota` VALUES (3302, 'KABUPATEN BANYUMAS', 0);
INSERT INTO `tbl_m_kota` VALUES (3303, 'KABUPATEN PURBALINGGA', 0);
INSERT INTO `tbl_m_kota` VALUES (3304, 'KABUPATEN BANJARNEGARA', 0);
INSERT INTO `tbl_m_kota` VALUES (3305, 'KABUPATEN KEBUMEN', 0);
INSERT INTO `tbl_m_kota` VALUES (3306, 'KABUPATEN PURWOREJO', 0);
INSERT INTO `tbl_m_kota` VALUES (3307, 'KABUPATEN WONOSOBO', 0);
INSERT INTO `tbl_m_kota` VALUES (3308, 'KABUPATEN MAGELANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3309, 'KABUPATEN BOYOLALI', 0);
INSERT INTO `tbl_m_kota` VALUES (3310, 'KABUPATEN KLATEN', 0);
INSERT INTO `tbl_m_kota` VALUES (3311, 'KABUPATEN SUKOHARJO', 0);
INSERT INTO `tbl_m_kota` VALUES (3312, 'KABUPATEN WONOGIRI', 0);
INSERT INTO `tbl_m_kota` VALUES (3313, 'KABUPATEN KARANGANYAR', 0);
INSERT INTO `tbl_m_kota` VALUES (3314, 'KABUPATEN SRAGEN', 0);
INSERT INTO `tbl_m_kota` VALUES (3315, 'KABUPATEN GROBOGAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3316, 'KABUPATEN BLORA', 0);
INSERT INTO `tbl_m_kota` VALUES (3317, 'KABUPATEN REMBANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3318, 'KABUPATEN PATI', 0);
INSERT INTO `tbl_m_kota` VALUES (3319, 'KABUPATEN KUDUS', 0);
INSERT INTO `tbl_m_kota` VALUES (3320, 'KABUPATEN JEPARA', 0);
INSERT INTO `tbl_m_kota` VALUES (3321, 'KABUPATEN DEMAK', 0);
INSERT INTO `tbl_m_kota` VALUES (3322, 'KABUPATEN SEMARANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3323, 'KABUPATEN TEMANGGUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (3324, 'KABUPATEN KENDAL', 0);
INSERT INTO `tbl_m_kota` VALUES (3325, 'KABUPATEN BATANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3326, 'KABUPATEN PEKALONGAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3327, 'KABUPATEN PEMALANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3328, 'KABUPATEN TEGAL', 0);
INSERT INTO `tbl_m_kota` VALUES (3329, 'KABUPATEN BREBES', 0);
INSERT INTO `tbl_m_kota` VALUES (3371, 'KOTA MAGELANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3372, 'KOTA SURAKARTA', 0);
INSERT INTO `tbl_m_kota` VALUES (3373, 'KOTA SALATIGA', 0);
INSERT INTO `tbl_m_kota` VALUES (3374, 'KOTA SEMARANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3375, 'KOTA PEKALONGAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3376, 'KOTA TEGAL', 0);
INSERT INTO `tbl_m_kota` VALUES (3401, 'KABUPATEN KULON PROGO', 0);
INSERT INTO `tbl_m_kota` VALUES (3402, 'KABUPATEN BANTUL', 0);
INSERT INTO `tbl_m_kota` VALUES (3403, 'KABUPATEN GUNUNG KIDUL', 0);
INSERT INTO `tbl_m_kota` VALUES (3404, 'KABUPATEN SLEMAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3471, 'KOTA YOGYAKARTA', 0);
INSERT INTO `tbl_m_kota` VALUES (3501, 'KABUPATEN PACITAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3502, 'KABUPATEN PONOROGO', 0);
INSERT INTO `tbl_m_kota` VALUES (3503, 'KABUPATEN TRENGGALEK', 0);
INSERT INTO `tbl_m_kota` VALUES (3504, 'KABUPATEN TULUNGAGUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (3505, 'KABUPATEN BLITAR', 0);
INSERT INTO `tbl_m_kota` VALUES (3506, 'KABUPATEN KEDIRI', 0);
INSERT INTO `tbl_m_kota` VALUES (3507, 'KABUPATEN MALANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3508, 'KABUPATEN LUMAJANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3509, 'KABUPATEN JEMBER', 0);
INSERT INTO `tbl_m_kota` VALUES (3510, 'KABUPATEN BANYUWANGI', 0);
INSERT INTO `tbl_m_kota` VALUES (3511, 'KABUPATEN BONDOWOSO', 0);
INSERT INTO `tbl_m_kota` VALUES (3512, 'KABUPATEN SITUBONDO', 0);
INSERT INTO `tbl_m_kota` VALUES (3513, 'KABUPATEN PROBOLINGGO', 0);
INSERT INTO `tbl_m_kota` VALUES (3514, 'KABUPATEN PASURUAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3515, 'KABUPATEN SIDOARJO', 0);
INSERT INTO `tbl_m_kota` VALUES (3516, 'KABUPATEN MOJOKERTO', 0);
INSERT INTO `tbl_m_kota` VALUES (3517, 'KABUPATEN JOMBANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3518, 'KABUPATEN NGANJUK', 0);
INSERT INTO `tbl_m_kota` VALUES (3519, 'KABUPATEN MADIUN', 0);
INSERT INTO `tbl_m_kota` VALUES (3520, 'KABUPATEN MAGETAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3521, 'KABUPATEN NGAWI', 0);
INSERT INTO `tbl_m_kota` VALUES (3522, 'KABUPATEN BOJONEGORO', 0);
INSERT INTO `tbl_m_kota` VALUES (3523, 'KABUPATEN TUBAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3524, 'KABUPATEN LAMONGAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3525, 'KABUPATEN GRESIK', 0);
INSERT INTO `tbl_m_kota` VALUES (3526, 'KABUPATEN BANGKALAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3527, 'KABUPATEN SAMPANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3528, 'KABUPATEN PAMEKASAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3529, 'KABUPATEN SUMENEP', 0);
INSERT INTO `tbl_m_kota` VALUES (3571, 'KOTA KEDIRI', 0);
INSERT INTO `tbl_m_kota` VALUES (3572, 'KOTA BLITAR', 0);
INSERT INTO `tbl_m_kota` VALUES (3573, 'KOTA MALANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3574, 'KOTA PROBOLINGGO', 0);
INSERT INTO `tbl_m_kota` VALUES (3575, 'KOTA PASURUAN', 0);
INSERT INTO `tbl_m_kota` VALUES (3576, 'KOTA MOJOKERTO', 0);
INSERT INTO `tbl_m_kota` VALUES (3577, 'KOTA MADIUN', 0);
INSERT INTO `tbl_m_kota` VALUES (3578, 'KOTA SURABAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (3579, 'KOTA BATU', 0);
INSERT INTO `tbl_m_kota` VALUES (3601, 'KABUPATEN PANDEGLANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3602, 'KABUPATEN LEBAK', 0);
INSERT INTO `tbl_m_kota` VALUES (3603, 'KABUPATEN TANGERANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3604, 'KABUPATEN SERANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3671, 'KOTA TANGERANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3672, 'KOTA CILEGON', 0);
INSERT INTO `tbl_m_kota` VALUES (3673, 'KOTA SERANG', 0);
INSERT INTO `tbl_m_kota` VALUES (3674, 'KOTA TANGERANG SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (5101, 'KABUPATEN JEMBRANA', 0);
INSERT INTO `tbl_m_kota` VALUES (5102, 'KABUPATEN TABANAN', 0);
INSERT INTO `tbl_m_kota` VALUES (5103, 'KABUPATEN BADUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (5104, 'KABUPATEN GIANYAR', 0);
INSERT INTO `tbl_m_kota` VALUES (5105, 'KABUPATEN KLUNGKUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (5106, 'KABUPATEN BANGLI', 0);
INSERT INTO `tbl_m_kota` VALUES (5107, 'KABUPATEN KARANG ASEM', 0);
INSERT INTO `tbl_m_kota` VALUES (5108, 'KABUPATEN BULELENG', 0);
INSERT INTO `tbl_m_kota` VALUES (5171, 'KOTA DENPASAR', 0);
INSERT INTO `tbl_m_kota` VALUES (5201, 'KABUPATEN LOMBOK BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (5202, 'KABUPATEN LOMBOK TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (5203, 'KABUPATEN LOMBOK TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (5204, 'KABUPATEN SUMBAWA', 0);
INSERT INTO `tbl_m_kota` VALUES (5205, 'KABUPATEN DOMPU', 0);
INSERT INTO `tbl_m_kota` VALUES (5206, 'KABUPATEN BIMA', 0);
INSERT INTO `tbl_m_kota` VALUES (5207, 'KABUPATEN SUMBAWA BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (5208, 'KABUPATEN LOMBOK UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (5271, 'KOTA MATARAM', 0);
INSERT INTO `tbl_m_kota` VALUES (5272, 'KOTA BIMA', 0);
INSERT INTO `tbl_m_kota` VALUES (5301, 'KABUPATEN SUMBA BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (5302, 'KABUPATEN SUMBA TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (5303, 'KABUPATEN KUPANG', 0);
INSERT INTO `tbl_m_kota` VALUES (5304, 'KABUPATEN TIMOR TENGAH SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (5305, 'KABUPATEN TIMOR TENGAH UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (5306, 'KABUPATEN BELU', 0);
INSERT INTO `tbl_m_kota` VALUES (5307, 'KABUPATEN ALOR', 0);
INSERT INTO `tbl_m_kota` VALUES (5308, 'KABUPATEN LEMBATA', 0);
INSERT INTO `tbl_m_kota` VALUES (5309, 'KABUPATEN FLORES TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (5310, 'KABUPATEN SIKKA', 0);
INSERT INTO `tbl_m_kota` VALUES (5311, 'KABUPATEN ENDE', 0);
INSERT INTO `tbl_m_kota` VALUES (5312, 'KABUPATEN NGADA', 0);
INSERT INTO `tbl_m_kota` VALUES (5313, 'KABUPATEN MANGGARAI', 0);
INSERT INTO `tbl_m_kota` VALUES (5314, 'KABUPATEN ROTE NDAO', 0);
INSERT INTO `tbl_m_kota` VALUES (5315, 'KABUPATEN MANGGARAI BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (5316, 'KABUPATEN SUMBA TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (5317, 'KABUPATEN SUMBA BARAT DAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (5318, 'KABUPATEN NAGEKEO', 0);
INSERT INTO `tbl_m_kota` VALUES (5319, 'KABUPATEN MANGGARAI TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (5320, 'KABUPATEN SABU RAIJUA', 0);
INSERT INTO `tbl_m_kota` VALUES (5321, 'KABUPATEN MALAKA', 0);
INSERT INTO `tbl_m_kota` VALUES (5371, 'KOTA KUPANG', 0);
INSERT INTO `tbl_m_kota` VALUES (6101, 'KABUPATEN SAMBAS', 0);
INSERT INTO `tbl_m_kota` VALUES (6102, 'KABUPATEN BENGKAYANG', 0);
INSERT INTO `tbl_m_kota` VALUES (6103, 'KABUPATEN LANDAK', 0);
INSERT INTO `tbl_m_kota` VALUES (6104, 'KABUPATEN MEMPAWAH', 0);
INSERT INTO `tbl_m_kota` VALUES (6105, 'KABUPATEN SANGGAU', 0);
INSERT INTO `tbl_m_kota` VALUES (6106, 'KABUPATEN KETAPANG', 0);
INSERT INTO `tbl_m_kota` VALUES (6107, 'KABUPATEN SINTANG', 0);
INSERT INTO `tbl_m_kota` VALUES (6108, 'KABUPATEN KAPUAS HULU', 0);
INSERT INTO `tbl_m_kota` VALUES (6109, 'KABUPATEN SEKADAU', 0);
INSERT INTO `tbl_m_kota` VALUES (6110, 'KABUPATEN MELAWI', 0);
INSERT INTO `tbl_m_kota` VALUES (6111, 'KABUPATEN KAYONG UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (6112, 'KABUPATEN KUBU RAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (6171, 'KOTA PONTIANAK', 0);
INSERT INTO `tbl_m_kota` VALUES (6172, 'KOTA SINGKAWANG', 0);
INSERT INTO `tbl_m_kota` VALUES (6201, 'KABUPATEN KOTAWARINGIN BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (6202, 'KABUPATEN KOTAWARINGIN TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (6203, 'KABUPATEN KAPUAS', 0);
INSERT INTO `tbl_m_kota` VALUES (6204, 'KABUPATEN BARITO SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (6205, 'KABUPATEN BARITO UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (6206, 'KABUPATEN SUKAMARA', 0);
INSERT INTO `tbl_m_kota` VALUES (6207, 'KABUPATEN LAMANDAU', 0);
INSERT INTO `tbl_m_kota` VALUES (6208, 'KABUPATEN SERUYAN', 0);
INSERT INTO `tbl_m_kota` VALUES (6209, 'KABUPATEN KATINGAN', 0);
INSERT INTO `tbl_m_kota` VALUES (6210, 'KABUPATEN PULANG PISAU', 0);
INSERT INTO `tbl_m_kota` VALUES (6211, 'KABUPATEN GUNUNG MAS', 0);
INSERT INTO `tbl_m_kota` VALUES (6212, 'KABUPATEN BARITO TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (6213, 'KABUPATEN MURUNG RAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (6271, 'KOTA PALANGKA RAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (6301, 'KABUPATEN TANAH LAUT', 0);
INSERT INTO `tbl_m_kota` VALUES (6302, 'KABUPATEN KOTA BARU', 0);
INSERT INTO `tbl_m_kota` VALUES (6303, 'KABUPATEN BANJAR', 0);
INSERT INTO `tbl_m_kota` VALUES (6304, 'KABUPATEN BARITO KUALA', 0);
INSERT INTO `tbl_m_kota` VALUES (6305, 'KABUPATEN TAPIN', 0);
INSERT INTO `tbl_m_kota` VALUES (6306, 'KABUPATEN HULU SUNGAI SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (6307, 'KABUPATEN HULU SUNGAI TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (6308, 'KABUPATEN HULU SUNGAI UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (6309, 'KABUPATEN TABALONG', 0);
INSERT INTO `tbl_m_kota` VALUES (6310, 'KABUPATEN TANAH BUMBU', 0);
INSERT INTO `tbl_m_kota` VALUES (6311, 'KABUPATEN BALANGAN', 0);
INSERT INTO `tbl_m_kota` VALUES (6371, 'KOTA BANJARMASIN', 0);
INSERT INTO `tbl_m_kota` VALUES (6372, 'KOTA BANJAR BARU', 0);
INSERT INTO `tbl_m_kota` VALUES (6401, 'KABUPATEN PASER', 0);
INSERT INTO `tbl_m_kota` VALUES (6402, 'KABUPATEN KUTAI BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (6403, 'KABUPATEN KUTAI KARTANEGARA', 0);
INSERT INTO `tbl_m_kota` VALUES (6404, 'KABUPATEN KUTAI TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (6405, 'KABUPATEN BERAU', 0);
INSERT INTO `tbl_m_kota` VALUES (6409, 'KABUPATEN PENAJAM PASER UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (6411, 'KABUPATEN MAHAKAM HULU', 0);
INSERT INTO `tbl_m_kota` VALUES (6471, 'KOTA BALIKPAPAN', 0);
INSERT INTO `tbl_m_kota` VALUES (6472, 'KOTA SAMARINDA', 0);
INSERT INTO `tbl_m_kota` VALUES (6474, 'KOTA BONTANG', 0);
INSERT INTO `tbl_m_kota` VALUES (6501, 'KABUPATEN MALINAU', 0);
INSERT INTO `tbl_m_kota` VALUES (6502, 'KABUPATEN BULUNGAN', 0);
INSERT INTO `tbl_m_kota` VALUES (6503, 'KABUPATEN TANA TIDUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (6504, 'KABUPATEN NUNUKAN', 0);
INSERT INTO `tbl_m_kota` VALUES (6571, 'KOTA TARAKAN', 0);
INSERT INTO `tbl_m_kota` VALUES (7101, 'KABUPATEN BOLAANG MONGONDOW', 0);
INSERT INTO `tbl_m_kota` VALUES (7102, 'KABUPATEN MINAHASA', 0);
INSERT INTO `tbl_m_kota` VALUES (7103, 'KABUPATEN KEPULAUAN SANGIHE', 0);
INSERT INTO `tbl_m_kota` VALUES (7104, 'KABUPATEN KEPULAUAN TALAUD', 0);
INSERT INTO `tbl_m_kota` VALUES (7105, 'KABUPATEN MINAHASA SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (7106, 'KABUPATEN MINAHASA UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7107, 'KABUPATEN BOLAANG MONGONDOW UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7108, 'KABUPATEN SIAU TAGULANDANG BIARO', 0);
INSERT INTO `tbl_m_kota` VALUES (7109, 'KABUPATEN MINAHASA TENGGARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7110, 'KABUPATEN BOLAANG MONGONDOW SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (7111, 'KABUPATEN BOLAANG MONGONDOW TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (7171, 'KOTA MANADO', 0);
INSERT INTO `tbl_m_kota` VALUES (7172, 'KOTA BITUNG', 0);
INSERT INTO `tbl_m_kota` VALUES (7173, 'KOTA TOMOHON', 0);
INSERT INTO `tbl_m_kota` VALUES (7174, 'KOTA KOTAMOBAGU', 0);
INSERT INTO `tbl_m_kota` VALUES (7201, 'KABUPATEN BANGGAI KEPULAUAN', 0);
INSERT INTO `tbl_m_kota` VALUES (7202, 'KABUPATEN BANGGAI', 0);
INSERT INTO `tbl_m_kota` VALUES (7203, 'KABUPATEN MOROWALI', 0);
INSERT INTO `tbl_m_kota` VALUES (7204, 'KABUPATEN POSO', 0);
INSERT INTO `tbl_m_kota` VALUES (7205, 'KABUPATEN DONGGALA', 0);
INSERT INTO `tbl_m_kota` VALUES (7206, 'KABUPATEN TOLI-TOLI', 0);
INSERT INTO `tbl_m_kota` VALUES (7207, 'KABUPATEN BUOL', 0);
INSERT INTO `tbl_m_kota` VALUES (7208, 'KABUPATEN PARIGI MOUTONG', 0);
INSERT INTO `tbl_m_kota` VALUES (7209, 'KABUPATEN TOJO UNA-UNA', 0);
INSERT INTO `tbl_m_kota` VALUES (7210, 'KABUPATEN SIGI', 0);
INSERT INTO `tbl_m_kota` VALUES (7211, 'KABUPATEN BANGGAI LAUT', 0);
INSERT INTO `tbl_m_kota` VALUES (7212, 'KABUPATEN MOROWALI UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7271, 'KOTA PALU', 0);
INSERT INTO `tbl_m_kota` VALUES (7301, 'KABUPATEN KEPULAUAN SELAYAR', 0);
INSERT INTO `tbl_m_kota` VALUES (7302, 'KABUPATEN BULUKUMBA', 0);
INSERT INTO `tbl_m_kota` VALUES (7303, 'KABUPATEN BANTAENG', 0);
INSERT INTO `tbl_m_kota` VALUES (7304, 'KABUPATEN JENEPONTO', 0);
INSERT INTO `tbl_m_kota` VALUES (7305, 'KABUPATEN TAKALAR', 0);
INSERT INTO `tbl_m_kota` VALUES (7306, 'KABUPATEN GOWA', 0);
INSERT INTO `tbl_m_kota` VALUES (7307, 'KABUPATEN SINJAI', 0);
INSERT INTO `tbl_m_kota` VALUES (7308, 'KABUPATEN MAROS', 0);
INSERT INTO `tbl_m_kota` VALUES (7309, 'KABUPATEN PANGKAJENE DAN KEPULAUAN', 0);
INSERT INTO `tbl_m_kota` VALUES (7310, 'KABUPATEN BARRU', 0);
INSERT INTO `tbl_m_kota` VALUES (7311, 'KABUPATEN BONE', 0);
INSERT INTO `tbl_m_kota` VALUES (7312, 'KABUPATEN SOPPENG', 0);
INSERT INTO `tbl_m_kota` VALUES (7313, 'KABUPATEN WAJO', 0);
INSERT INTO `tbl_m_kota` VALUES (7314, 'KABUPATEN SIDENRENG RAPPANG', 0);
INSERT INTO `tbl_m_kota` VALUES (7315, 'KABUPATEN PINRANG', 0);
INSERT INTO `tbl_m_kota` VALUES (7316, 'KABUPATEN ENREKANG', 0);
INSERT INTO `tbl_m_kota` VALUES (7317, 'KABUPATEN LUWU', 0);
INSERT INTO `tbl_m_kota` VALUES (7318, 'KABUPATEN TANA TORAJA', 0);
INSERT INTO `tbl_m_kota` VALUES (7322, 'KABUPATEN LUWU UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7325, 'KABUPATEN LUWU TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (7326, 'KABUPATEN TORAJA UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7371, 'KOTA MAKASSAR', 0);
INSERT INTO `tbl_m_kota` VALUES (7372, 'KOTA PAREPARE', 0);
INSERT INTO `tbl_m_kota` VALUES (7373, 'KOTA PALOPO', 0);
INSERT INTO `tbl_m_kota` VALUES (7401, 'KABUPATEN BUTON', 0);
INSERT INTO `tbl_m_kota` VALUES (7402, 'KABUPATEN MUNA', 0);
INSERT INTO `tbl_m_kota` VALUES (7403, 'KABUPATEN KONAWE', 0);
INSERT INTO `tbl_m_kota` VALUES (7404, 'KABUPATEN KOLAKA', 0);
INSERT INTO `tbl_m_kota` VALUES (7405, 'KABUPATEN KONAWE SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (7406, 'KABUPATEN BOMBANA', 0);
INSERT INTO `tbl_m_kota` VALUES (7407, 'KABUPATEN WAKATOBI', 0);
INSERT INTO `tbl_m_kota` VALUES (7408, 'KABUPATEN KOLAKA UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7409, 'KABUPATEN BUTON UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7410, 'KABUPATEN KONAWE UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7411, 'KABUPATEN KOLAKA TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (7412, 'KABUPATEN KONAWE KEPULAUAN', 0);
INSERT INTO `tbl_m_kota` VALUES (7413, 'KABUPATEN MUNA BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (7414, 'KABUPATEN BUTON TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (7415, 'KABUPATEN BUTON SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (7471, 'KOTA KENDARI', 0);
INSERT INTO `tbl_m_kota` VALUES (7472, 'KOTA BAUBAU', 0);
INSERT INTO `tbl_m_kota` VALUES (7501, 'KABUPATEN BOALEMO', 0);
INSERT INTO `tbl_m_kota` VALUES (7502, 'KABUPATEN GORONTALO', 0);
INSERT INTO `tbl_m_kota` VALUES (7503, 'KABUPATEN POHUWATO', 0);
INSERT INTO `tbl_m_kota` VALUES (7504, 'KABUPATEN BONE BOLANGO', 0);
INSERT INTO `tbl_m_kota` VALUES (7505, 'KABUPATEN GORONTALO UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7571, 'KOTA GORONTALO', 0);
INSERT INTO `tbl_m_kota` VALUES (7601, 'KABUPATEN MAJENE', 0);
INSERT INTO `tbl_m_kota` VALUES (7602, 'KABUPATEN POLEWALI MANDAR', 0);
INSERT INTO `tbl_m_kota` VALUES (7603, 'KABUPATEN MAMASA', 0);
INSERT INTO `tbl_m_kota` VALUES (7604, 'KABUPATEN MAMUJU', 0);
INSERT INTO `tbl_m_kota` VALUES (7605, 'KABUPATEN MAMUJU UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (7606, 'KABUPATEN MAMUJU TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (8101, 'KABUPATEN MALUKU TENGGARA BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (8102, 'KABUPATEN MALUKU TENGGARA', 0);
INSERT INTO `tbl_m_kota` VALUES (8103, 'KABUPATEN MALUKU TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (8104, 'KABUPATEN BURU', 0);
INSERT INTO `tbl_m_kota` VALUES (8105, 'KABUPATEN KEPULAUAN ARU', 0);
INSERT INTO `tbl_m_kota` VALUES (8106, 'KABUPATEN SERAM BAGIAN BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (8107, 'KABUPATEN SERAM BAGIAN TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (8108, 'KABUPATEN MALUKU BARAT DAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (8109, 'KABUPATEN BURU SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (8171, 'KOTA AMBON', 0);
INSERT INTO `tbl_m_kota` VALUES (8172, 'KOTA TUAL', 0);
INSERT INTO `tbl_m_kota` VALUES (8201, 'KABUPATEN HALMAHERA BARAT', 0);
INSERT INTO `tbl_m_kota` VALUES (8202, 'KABUPATEN HALMAHERA TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (8203, 'KABUPATEN KEPULAUAN SULA', 0);
INSERT INTO `tbl_m_kota` VALUES (8204, 'KABUPATEN HALMAHERA SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (8205, 'KABUPATEN HALMAHERA UTARA', 0);
INSERT INTO `tbl_m_kota` VALUES (8206, 'KABUPATEN HALMAHERA TIMUR', 0);
INSERT INTO `tbl_m_kota` VALUES (8207, 'KABUPATEN PULAU MOROTAI', 0);
INSERT INTO `tbl_m_kota` VALUES (8208, 'KABUPATEN PULAU TALIABU', 0);
INSERT INTO `tbl_m_kota` VALUES (8271, 'KOTA TERNATE', 0);
INSERT INTO `tbl_m_kota` VALUES (8272, 'KOTA TIDORE KEPULAUAN', 0);
INSERT INTO `tbl_m_kota` VALUES (9101, 'KABUPATEN FAKFAK', 0);
INSERT INTO `tbl_m_kota` VALUES (9102, 'KABUPATEN KAIMANA', 0);
INSERT INTO `tbl_m_kota` VALUES (9103, 'KABUPATEN TELUK WONDAMA', 0);
INSERT INTO `tbl_m_kota` VALUES (9104, 'KABUPATEN TELUK BINTUNI', 0);
INSERT INTO `tbl_m_kota` VALUES (9105, 'KABUPATEN MANOKWARI', 0);
INSERT INTO `tbl_m_kota` VALUES (9106, 'KABUPATEN SORONG SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (9107, 'KABUPATEN SORONG', 0);
INSERT INTO `tbl_m_kota` VALUES (9108, 'KABUPATEN RAJA AMPAT', 0);
INSERT INTO `tbl_m_kota` VALUES (9109, 'KABUPATEN TAMBRAUW', 0);
INSERT INTO `tbl_m_kota` VALUES (9110, 'KABUPATEN MAYBRAT', 0);
INSERT INTO `tbl_m_kota` VALUES (9111, 'KABUPATEN MANOKWARI SELATAN', 0);
INSERT INTO `tbl_m_kota` VALUES (9112, 'KABUPATEN PEGUNUNGAN ARFAK', 0);
INSERT INTO `tbl_m_kota` VALUES (9171, 'KOTA SORONG', 0);
INSERT INTO `tbl_m_kota` VALUES (9401, 'KABUPATEN MERAUKE', 0);
INSERT INTO `tbl_m_kota` VALUES (9402, 'KABUPATEN JAYAWIJAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (9403, 'KABUPATEN JAYAPURA', 0);
INSERT INTO `tbl_m_kota` VALUES (9404, 'KABUPATEN NABIRE', 0);
INSERT INTO `tbl_m_kota` VALUES (9408, 'KABUPATEN KEPULAUAN YAPEN', 0);
INSERT INTO `tbl_m_kota` VALUES (9409, 'KABUPATEN BIAK NUMFOR', 0);
INSERT INTO `tbl_m_kota` VALUES (9410, 'KABUPATEN PANIAI', 0);
INSERT INTO `tbl_m_kota` VALUES (9411, 'KABUPATEN PUNCAK JAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (9412, 'KABUPATEN MIMIKA', 0);
INSERT INTO `tbl_m_kota` VALUES (9413, 'KABUPATEN BOVEN DIGOEL', 0);
INSERT INTO `tbl_m_kota` VALUES (9414, 'KABUPATEN MAPPI', 0);
INSERT INTO `tbl_m_kota` VALUES (9415, 'KABUPATEN ASMAT', 0);
INSERT INTO `tbl_m_kota` VALUES (9416, 'KABUPATEN YAHUKIMO', 0);
INSERT INTO `tbl_m_kota` VALUES (9417, 'KABUPATEN PEGUNUNGAN BINTANG', 0);
INSERT INTO `tbl_m_kota` VALUES (9418, 'KABUPATEN TOLIKARA', 0);
INSERT INTO `tbl_m_kota` VALUES (9419, 'KABUPATEN SARMI', 0);
INSERT INTO `tbl_m_kota` VALUES (9420, 'KABUPATEN KEEROM', 0);
INSERT INTO `tbl_m_kota` VALUES (9426, 'KABUPATEN WAROPEN', 0);
INSERT INTO `tbl_m_kota` VALUES (9427, 'KABUPATEN SUPIORI', 0);
INSERT INTO `tbl_m_kota` VALUES (9428, 'KABUPATEN MAMBERAMO RAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (9429, 'KABUPATEN NDUGA', 0);
INSERT INTO `tbl_m_kota` VALUES (9430, 'KABUPATEN LANNY JAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (9431, 'KABUPATEN MAMBERAMO TENGAH', 0);
INSERT INTO `tbl_m_kota` VALUES (9432, 'KABUPATEN YALIMO', 0);
INSERT INTO `tbl_m_kota` VALUES (9433, 'KABUPATEN PUNCAK', 0);
INSERT INTO `tbl_m_kota` VALUES (9434, 'KABUPATEN DOGIYAI', 0);
INSERT INTO `tbl_m_kota` VALUES (9435, 'KABUPATEN INTAN JAYA', 0);
INSERT INTO `tbl_m_kota` VALUES (9436, 'KABUPATEN DEIYAI', 0);
INSERT INTO `tbl_m_kota` VALUES (9471, 'KOTA JAYAPURA', 0);

-- ----------------------------
-- Table structure for tbl_m_main_cat
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_main_cat`;
CREATE TABLE `tbl_m_main_cat`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name_main_cat` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `stat_main_cat` int(11) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 2 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_main_cat
-- ----------------------------
INSERT INTO `tbl_m_main_cat` VALUES (1, 'MOBIL', 1);

-- ----------------------------
-- Table structure for tbl_m_menu
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_menu`;
CREATE TABLE `tbl_m_menu`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `menu_param` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `menu_value` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `menu_cat` enum('MASTER','ACCOUNT','REQUEST','SYSTEM') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 23 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_menu
-- ----------------------------
INSERT INTO `tbl_m_menu` VALUES (1, 'Main Category', 'mcategory', 'MASTER');
INSERT INTO `tbl_m_menu` VALUES (2, 'Sub Category', 'category', 'MASTER');
INSERT INTO `tbl_m_menu` VALUES (3, 'Brand', 'brand', 'MASTER');
INSERT INTO `tbl_m_menu` VALUES (4, 'Model', 'model', 'MASTER');
INSERT INTO `tbl_m_menu` VALUES (5, 'Type', 'type', 'MASTER');
INSERT INTO `tbl_m_menu` VALUES (6, 'Payment Method', 'payment', 'MASTER');
INSERT INTO `tbl_m_menu` VALUES (7, 'Tenor', 'tenor', 'MASTER');
INSERT INTO `tbl_m_menu` VALUES (8, 'City', 'city', 'MASTER');
INSERT INTO `tbl_m_menu` VALUES (9, 'User Level', 'user-grade', 'ACCOUNT');
INSERT INTO `tbl_m_menu` VALUES (10, 'User Account', 'user-account', 'ACCOUNT');
INSERT INTO `tbl_m_menu` VALUES (11, 'Customer', 'cutomer', 'ACCOUNT');
INSERT INTO `tbl_m_menu` VALUES (12, 'Seller Admin', 'seller-adm', 'ACCOUNT');
INSERT INTO `tbl_m_menu` VALUES (13, 'Seller', 'seller', 'ACCOUNT');
INSERT INTO `tbl_m_menu` VALUES (14, 'All Request', 'all-request', 'REQUEST');
INSERT INTO `tbl_m_menu` VALUES (15, 'All Offers', 'all-offers', 'REQUEST');
INSERT INTO `tbl_m_menu` VALUES (16, 'All Payment', 'all-payment', 'REQUEST');
INSERT INTO `tbl_m_menu` VALUES (17, 'Send Notification', 'send-notification', 'REQUEST');
INSERT INTO `tbl_m_menu` VALUES (18, 'Notification', 'notif', '');
INSERT INTO `tbl_m_menu` VALUES (19, 'Log', 'log', 'SYSTEM');
INSERT INTO `tbl_m_menu` VALUES (20, 'System', 'system-log', 'SYSTEM');

-- ----------------------------
-- Table structure for tbl_m_menu_admin
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_menu_admin`;
CREATE TABLE `tbl_m_menu_admin`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `menu_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `menu_param` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tbl_m_merk
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_merk`;
CREATE TABLE `tbl_m_merk`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cat` int(11) NULL DEFAULT NULL,
  `name_merk` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_merk` int(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 9 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_merk
-- ----------------------------
INSERT INTO `tbl_m_merk` VALUES (1, 10, 'Mobil Baru', 1);
INSERT INTO `tbl_m_merk` VALUES (2, 10, 'Mobil Bekas', 1);
INSERT INTO `tbl_m_merk` VALUES (3, 10, 'Mobil SUV 1', 1);
INSERT INTO `tbl_m_merk` VALUES (4, 10, 'Mobil Baru', 1);
INSERT INTO `tbl_m_merk` VALUES (5, 10, 'Mobil Bekas', 1);
INSERT INTO `tbl_m_merk` VALUES (6, 10, 'Mobil Baru', 1);
INSERT INTO `tbl_m_merk` VALUES (7, 10, 'Mobil Bekas', 1);
INSERT INTO `tbl_m_merk` VALUES (8, 13, 'Beat', 1);

-- ----------------------------
-- Table structure for tbl_m_model
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_model`;
CREATE TABLE `tbl_m_model`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_merk` int(11) NULL DEFAULT NULL,
  `name_model` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_model` int(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 14 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_model
-- ----------------------------
INSERT INTO `tbl_m_model` VALUES (1, 8, 'CRV', 1);
INSERT INTO `tbl_m_model` VALUES (2, 1, 'Mobilio1', 1);
INSERT INTO `tbl_m_model` VALUES (3, 10, 'Livina', 1);
INSERT INTO `tbl_m_model` VALUES (4, 12, 'Fortuner', 1);
INSERT INTO `tbl_m_model` VALUES (5, 10, 'CRV', 1);
INSERT INTO `tbl_m_model` VALUES (6, 10, 'Mobilio', 1);
INSERT INTO `tbl_m_model` VALUES (7, 10, 'Livina', 1);
INSERT INTO `tbl_m_model` VALUES (8, 12, 'Fortuner', 1);
INSERT INTO `tbl_m_model` VALUES (9, 10, 'CRV', 1);
INSERT INTO `tbl_m_model` VALUES (10, 10, 'Mobilio', 1);
INSERT INTO `tbl_m_model` VALUES (11, 10, 'Livina', 1);
INSERT INTO `tbl_m_model` VALUES (12, 12, 'Fortuner', 1);
INSERT INTO `tbl_m_model` VALUES (13, 8, '150 CC', 1);

-- ----------------------------
-- Table structure for tbl_m_payment
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_payment`;
CREATE TABLE `tbl_m_payment`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `payment_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_payment` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_payment
-- ----------------------------
INSERT INTO `tbl_m_payment` VALUES (1, 'cash1', 1);
INSERT INTO `tbl_m_payment` VALUES (4, 'TRF', 1);

-- ----------------------------
-- Table structure for tbl_m_subcat
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_subcat`;
CREATE TABLE `tbl_m_subcat`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_cat` int(11) NULL DEFAULT NULL,
  `name_sub_cat` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_subcat` int(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 14 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_subcat
-- ----------------------------
INSERT INTO `tbl_m_subcat` VALUES (1, 1, 'Category 03', 1);
INSERT INTO `tbl_m_subcat` VALUES (2, 2, 'Category 07', 1);
INSERT INTO `tbl_m_subcat` VALUES (3, 3, 'Category 08', 1);
INSERT INTO `tbl_m_subcat` VALUES (4, 2, 'Category 999', 1);
INSERT INTO `tbl_m_subcat` VALUES (5, 3, 'Category 666', 0);
INSERT INTO `tbl_m_subcat` VALUES (6, 2, 'Category 55', 1);
INSERT INTO `tbl_m_subcat` VALUES (7, 2, 'Category 66', 0);
INSERT INTO `tbl_m_subcat` VALUES (8, 3, 'Category Test', 1);
INSERT INTO `tbl_m_subcat` VALUES (9, 4, 'Category Test Chield', 1);
INSERT INTO `tbl_m_subcat` VALUES (10, 2, 'Mobil1', 1);
INSERT INTO `tbl_m_subcat` VALUES (11, 3, 'Name', 0);
INSERT INTO `tbl_m_subcat` VALUES (13, NULL, 'Honda', 1);

-- ----------------------------
-- Table structure for tbl_m_tenor
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_tenor`;
CREATE TABLE `tbl_m_tenor`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenor` int(11) NULL DEFAULT NULL,
  `tenor_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_tenor` int(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 14 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_tenor
-- ----------------------------
INSERT INTO `tbl_m_tenor` VALUES (1, 59, '59 Bulan', 0);
INSERT INTO `tbl_m_tenor` VALUES (2, 11, '11 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (3, 1, '01 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (4, 2, '2 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (5, 20, '20 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (6, 12, '12 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (7, 2000000, '2000000 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (8, 2000000, '2000000 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (9, 19, '19 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (10, 2, '2 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (11, 1, '1 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (12, 1, '01 Bulan', 1);
INSERT INTO `tbl_m_tenor` VALUES (13, 11111, '11111 Bulan', 1);

-- ----------------------------
-- Table structure for tbl_m_type
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_type`;
CREATE TABLE `tbl_m_type`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_model` int(11) NULL DEFAULT NULL,
  `name_type` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_type` int(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 5 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_type
-- ----------------------------
INSERT INTO `tbl_m_type` VALUES (1, 13, '2.0L1', 1);
INSERT INTO `tbl_m_type` VALUES (2, 4, '2.4 G M/T', 1);
INSERT INTO `tbl_m_type` VALUES (3, 13, 'Matic', 1);
INSERT INTO `tbl_m_type` VALUES (4, 13, 'Matic', 1);

-- ----------------------------
-- Table structure for tbl_m_user
-- ----------------------------
DROP TABLE IF EXISTS `tbl_m_user`;
CREATE TABLE `tbl_m_user`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `user_id` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `email` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `password` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `remember_token` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `phone_no` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `address` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `notif_email` int(1) NULL DEFAULT 0,
  `access_menu` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `id_grade` int(1) NULL DEFAULT NULL,
  `access_grade` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `id_seller_adm` int(11) NULL DEFAULT NULL,
  `verify_otp` int(11) NULL DEFAULT 0,
  `user_status` int(1) NULL DEFAULT 1,
  `create_at` datetime(0) NULL DEFAULT NULL,
  `update_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 101 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_m_user
-- ----------------------------
INSERT INTO `tbl_m_user` VALUES (1, 'Andre Pabertiyan', 'pabertiyan', 'info@solusiid.com', '$2y$10$2GkqanOMVc7EEP8Q6ZfKA.RerSUm3pTUqOlmLwMFyQw0L2d8plJiy', NULL, NULL, 'Jakarta', 0, '{\r\n   \"master\":[\r\n      {\r\n         \"menu_name\":\"Main Category\",\r\n         \"menu_param\":\"1\"\r\n      },{\r\n         \"menu_name\":\"Category\",\r\n         \"menu_param\":\"2\"\r\n      },\r\n	  {\r\n         \"menu_name\":\"Brand\",\r\n         \"menu_param\":\"3\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Model\",\r\n         \"menu_param\":\"4\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Type\",\r\n         \"menu_param\":\"5\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Payment Method\",\r\n         \"menu_param\":\"6\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Tenor\",\r\n         \"menu_param\":\"7\"\r\n      },\r\n      {\r\n         \"menu_name\":\"City\",\r\n         \"menu_param\":\"8\"\r\n      }\r\n   ],\r\n   \"account\":[\r\n      {\r\n         \"menu_name\":\"User Level\",\r\n         \"menu_param\":\"9\"\r\n      },\r\n      {\r\n         \"menu_name\":\"User Account\",\r\n         \"menu_param\":\"10\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Customer\",\r\n         \"menu_param\":\"11\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Seller Admin\",\r\n         \"menu_param\":\"12\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Seller\",\r\n         \"menu_param\":\"13\"\r\n      }\r\n   ],\r\n   \"request\":[\r\n      {\r\n         \"menu_name\":\"All Request\",\r\n         \"menu_param\":\"14\"\r\n      },\r\n      {\r\n         \"menu_name\":\"All Offers\",\r\n         \"menu_param\":\"15\"\r\n      },\r\n      {\r\n         \"menu_name\":\"All Payment\",\r\n         \"menu_param\":\"16\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Send Notification\",\r\n         \"menu_param\":\"17\"\r\n      }\r\n   ],\r\n   \"system\":[\r\n      {\r\n         \"menu_name\":\"Notification\",\r\n         \"menu_param\":\"18\"\r\n      },\r\n      {\r\n         \"menu_name\":\"Log\",\r\n         \"menu_param\":\"19\"\r\n      },\r\n      {\r\n         \"menu_name\":\"System\",\r\n         \"menu_param\":\"20\"\r\n      }\r\n   ]\r\n}', 0, '0', NULL, 0, 0, NULL, NULL);
INSERT INTO `tbl_m_user` VALUES (90, 'Pabertiyan', NULL, 'andrepabertiyan@gmail.com', '$2y$10$5TTy2KiW.DS/ySx0NBlZfeZcuMRT2adDhWS9XrhFSF/RyqBA7.IkC', NULL, '085659240195', NULL, 0, '{\"master\":[],\"account\":[],\"request\":[],\"system\":[]}', 1, '2', NULL, 0, 0, '2019-08-11 16:47:18', '2019-08-11 17:42:20');
INSERT INTO `tbl_m_user` VALUES (93, 'Customer', NULL, 'andrepabertiyan1@gmail.com', '$2y$10$5TTy2KiW.DS/ySx0NBlZfeZcuMRT2adDhWS9XrhFSF/RyqBA7.IkC', NULL, '085659240195', NULL, 1, NULL, 2, NULL, NULL, 0, 1, '2019-08-11 16:47:18', '2019-08-11 22:07:21');
INSERT INTO `tbl_m_user` VALUES (94, 'Seller Admin', NULL, 'andrepabertiyan2@gmail.com', '$2y$10$5TTy2KiW.DS/ySx0NBlZfeZcuMRT2adDhWS9XrhFSF/RyqBA7.IkC', NULL, '085659240195', 'W', 0, NULL, 3, NULL, NULL, 0, 1, '2019-08-11 16:47:18', '2019-08-11 19:02:04');
INSERT INTO `tbl_m_user` VALUES (95, 'Seller11', NULL, 'andrepabertiyan3@gmail.com', '$2y$10$5TTy2KiW.DS/ySx0NBlZfeZcuMRT2adDhWS9XrhFSF/RyqBA7.IkC', NULL, '085659240195', '2', 0, NULL, 4, NULL, 94, 0, 1, '2019-08-11 16:47:18', '2019-08-11 20:50:53');
INSERT INTO `tbl_m_user` VALUES (98, 'SELLER 1', NULL, 'seller@ggg.com', '$2y$10$G7qE44PBO2SIVsXT3M/UnOtEJUPTZ3BNnNXECNnbhJl7SLy4Tlf.C', NULL, '8', NULL, 0, NULL, 4, NULL, 94, 0, 1, '2019-08-11 20:06:49', NULL);
INSERT INTO `tbl_m_user` VALUES (99, 'SELLER 1', NULL, 'seller@ggg.com', '$2y$10$/jniQhKpng6qdMItfxV0GexM4R0i6.6zBlWTmTQk7ivJOpiNjM/J6', NULL, '8', NULL, 0, NULL, 4, NULL, 94, 0, 1, '2019-08-11 20:07:40', NULL);

-- ----------------------------
-- Table structure for tbl_r_email_notif
-- ----------------------------
DROP TABLE IF EXISTS `tbl_r_email_notif`;
CREATE TABLE `tbl_r_email_notif`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title_email` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `body_email` longtext CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `date_send` datetime(0) NULL DEFAULT NULL,
  `total_send` int(11) NULL DEFAULT NULL,
  `total_read` int(11) NULL DEFAULT NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tbl_r_log
-- ----------------------------
DROP TABLE IF EXISTS `tbl_r_log`;
CREATE TABLE `tbl_r_log`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `time_log` datetime(0) NULL DEFAULT NULL,
  `user_log` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `detail_log` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 77 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_r_log
-- ----------------------------
INSERT INTO `tbl_r_log` VALUES (1, '2019-08-11 19:25:49', 'info@solusiid.com', 'Access menu Brand');
INSERT INTO `tbl_r_log` VALUES (2, '2019-08-11 19:51:03', 'info@solusiid.com', 'Access Menu Request');
INSERT INTO `tbl_r_log` VALUES (3, '2019-08-11 19:51:10', 'info@solusiid.com', 'Access menu List Payment User');
INSERT INTO `tbl_r_log` VALUES (4, '2019-08-11 19:51:15', 'info@solusiid.com', 'Access Menu Log');
INSERT INTO `tbl_r_log` VALUES (5, '2019-08-11 19:52:08', 'info@solusiid.com', 'Access Menu Log');
INSERT INTO `tbl_r_log` VALUES (6, '2019-08-11 19:52:22', 'info@solusiid.com', 'Access Menu Log');
INSERT INTO `tbl_r_log` VALUES (7, '2019-08-11 19:52:25', 'info@solusiid.com', 'Access Menu Notif');
INSERT INTO `tbl_r_log` VALUES (8, '2019-08-11 19:52:25', 'info@solusiid.com', 'Access Menu Log OTP');
INSERT INTO `tbl_r_log` VALUES (9, '2019-08-11 19:52:31', 'info@solusiid.com', 'Access Menu Log');
INSERT INTO `tbl_r_log` VALUES (10, '2019-08-11 19:53:14', 'info@solusiid.com', 'Logout from system');
INSERT INTO `tbl_r_log` VALUES (11, '2019-08-11 19:53:34', 'andrepabertiyan2@gmail.com', 'Login to system');
INSERT INTO `tbl_r_log` VALUES (12, '2019-08-11 19:56:44', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (13, '2019-08-11 19:56:46', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (14, '2019-08-11 19:57:01', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (15, '2019-08-11 19:57:06', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (16, '2019-08-11 19:57:15', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (17, '2019-08-11 19:57:18', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (18, '2019-08-11 19:57:21', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (19, '2019-08-11 19:57:24', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (20, '2019-08-11 19:57:29', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (21, '2019-08-11 19:58:59', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (22, '2019-08-11 19:59:01', 'andrepabertiyan2@gmail.com', 'Access Menu Setting');
INSERT INTO `tbl_r_log` VALUES (23, '2019-08-11 20:01:56', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (24, '2019-08-11 20:04:06', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (25, '2019-08-11 20:04:46', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (26, '2019-08-11 20:05:26', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (27, '2019-08-11 20:06:21', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (28, '2019-08-11 20:06:49', 'andrepabertiyan2@gmail.com', 'Add Seller');
INSERT INTO `tbl_r_log` VALUES (29, '2019-08-11 20:06:50', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (30, '2019-08-11 20:07:40', 'andrepabertiyan2@gmail.com', 'Add Seller');
INSERT INTO `tbl_r_log` VALUES (31, '2019-08-11 20:07:40', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (32, '2019-08-11 20:07:44', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (33, '2019-08-11 20:07:57', 'andrepabertiyan2@gmail.com', 'Add Seller');
INSERT INTO `tbl_r_log` VALUES (34, '2019-08-11 20:07:57', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (35, '2019-08-11 20:09:25', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (36, '2019-08-11 20:09:29', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (37, '2019-08-11 20:09:46', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (38, '2019-08-11 20:15:23', 'andrepabertiyan2@gmail.com', 'Access Menu Request');
INSERT INTO `tbl_r_log` VALUES (39, '2019-08-11 20:17:17', 'andrepabertiyan2@gmail.com', 'Access Menu Request');
INSERT INTO `tbl_r_log` VALUES (40, '2019-08-11 20:17:47', 'andrepabertiyan2@gmail.com', 'Access Menu Request');
INSERT INTO `tbl_r_log` VALUES (41, '2019-08-11 20:18:44', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (42, '2019-08-11 20:19:08', 'andrepabertiyan2@gmail.com', 'Access Menu Request');
INSERT INTO `tbl_r_log` VALUES (43, '2019-08-11 20:19:16', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (44, '2019-08-11 20:20:10', 'andrepabertiyan2@gmail.com', 'Access menu Seller');
INSERT INTO `tbl_r_log` VALUES (45, '2019-08-11 20:20:26', 'andrepabertiyan2@gmail.com', 'Logout from system');
INSERT INTO `tbl_r_log` VALUES (46, '2019-08-11 20:20:41', 'andrepabertiyan3@gmail.com', 'Login to system');
INSERT INTO `tbl_r_log` VALUES (47, '2019-08-11 21:32:38', 'andrepabertiyan3@gmail.com', 'Access Menu Notification');
INSERT INTO `tbl_r_log` VALUES (48, '2019-08-11 21:48:21', 'andrepabertiyan3@gmail.com', 'Access Menu Notification');
INSERT INTO `tbl_r_log` VALUES (49, '2019-08-11 21:51:07', 'andrepabertiyan3@gmail.com', 'Access Menu Notification');
INSERT INTO `tbl_r_log` VALUES (50, '2019-08-11 21:52:51', 'andrepabertiyan3@gmail.com', 'Access Menu Notification');
INSERT INTO `tbl_r_log` VALUES (51, '2019-08-11 21:53:59', 'andrepabertiyan3@gmail.com', 'Logout from system');
INSERT INTO `tbl_r_log` VALUES (52, '2019-08-11 21:54:20', 'andrepabertiyan1@gmail.com', 'Login to system');
INSERT INTO `tbl_r_log` VALUES (53, '2019-08-11 21:57:30', 'andrepabertiyan1@gmail.com', 'Logout from system');
INSERT INTO `tbl_r_log` VALUES (54, '2019-08-11 21:57:46', 'andrepabertiyan3@gmail.com', 'Login to system');
INSERT INTO `tbl_r_log` VALUES (55, '2019-08-11 21:57:54', 'andrepabertiyan3@gmail.com', 'Logout from system');
INSERT INTO `tbl_r_log` VALUES (56, '2019-08-11 21:58:09', 'andrepabertiyan1@gmail.com', 'Login to system');
INSERT INTO `tbl_r_log` VALUES (57, '2019-08-11 22:07:26', 'andrepabertiyan1@gmail.com', 'Access Menu Request User');
INSERT INTO `tbl_r_log` VALUES (58, '2019-08-11 22:07:29', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (59, '2019-08-11 22:09:07', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (60, '2019-08-11 22:10:41', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (61, '2019-08-11 22:13:37', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (62, '2019-08-11 22:17:32', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (63, '2019-08-11 22:18:47', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (64, '2019-08-11 22:19:04', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (65, '2019-08-11 22:20:42', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (66, '2019-08-11 22:22:16', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (67, '2019-08-11 22:22:37', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (68, '2019-08-11 22:25:23', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (69, '2019-08-11 22:25:32', 'andrepabertiyan1@gmail.com', 'Confirm Down Payment');
INSERT INTO `tbl_r_log` VALUES (70, '2019-08-11 22:25:34', 'andrepabertiyan1@gmail.com', 'Access Menu Offers User');
INSERT INTO `tbl_r_log` VALUES (71, '2019-08-11 22:26:30', 'andrepabertiyan1@gmail.com', 'Access Menu Request User');
INSERT INTO `tbl_r_log` VALUES (72, '2019-08-11 22:27:39', 'andrepabertiyan1@gmail.com', 'Logout from system');
INSERT INTO `tbl_r_log` VALUES (73, '2019-08-11 22:27:47', 'andrepabertiyan2@gmail.com', 'Login to system');
INSERT INTO `tbl_r_log` VALUES (74, '2019-08-11 22:27:56', 'andrepabertiyan2@gmail.com', 'Access Menu Request');
INSERT INTO `tbl_r_log` VALUES (75, '2019-08-11 22:35:13', 'andrepabertiyan2@gmail.com', 'Logout from system');
INSERT INTO `tbl_r_log` VALUES (76, '2019-08-11 22:35:15', 'info@solusiid.com', 'Login to system');

-- ----------------------------
-- Table structure for tbl_r_notification
-- ----------------------------
DROP TABLE IF EXISTS `tbl_r_notification`;
CREATE TABLE `tbl_r_notification`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `no_offers` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `date_send` datetime(0) NULL DEFAULT NULL,
  `type_notif` enum('NEW_OFFERS','ACCEPT_OFFERS','PAYMENT_OFFER') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `sender_id` int(11) NULL DEFAULT NULL,
  `receiver_id` int(11) NULL DEFAULT NULL,
  `notification_detail` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `status_read` int(11) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_r_notification
-- ----------------------------
INSERT INTO `tbl_r_notification` VALUES (3, 'WTB20190811214322', '2019-08-11 21:43:22', 'PAYMENT_OFFER', 95, 93, 'New Offers from Seller11', 0);
INSERT INTO `tbl_r_notification` VALUES (4, 'WTB20190811225202', '2019-08-11 22:52:02', 'NEW_OFFERS', 1, 90, 'asd', 0);
INSERT INTO `tbl_r_notification` VALUES (5, 'WTB20190811225202', '2019-08-11 22:52:02', 'NEW_OFFERS', 1, 93, 'asd', 0);
INSERT INTO `tbl_r_notification` VALUES (6, 'WTB20190811225202', '2019-08-11 22:52:02', 'NEW_OFFERS', 1, 94, 'asd', 0);
INSERT INTO `tbl_r_notification` VALUES (7, 'WTB20190811225202', '2019-08-11 22:52:02', 'NEW_OFFERS', 1, 95, 'asd', 0);
INSERT INTO `tbl_r_notification` VALUES (8, 'WTB20190811225202', '2019-08-11 22:52:02', 'NEW_OFFERS', 1, 98, 'asd', 0);
INSERT INTO `tbl_r_notification` VALUES (9, 'WTB20190811225202', '2019-08-11 22:52:02', 'NEW_OFFERS', 1, 99, 'asd', 0);

-- ----------------------------
-- Table structure for tbl_r_otp
-- ----------------------------
DROP TABLE IF EXISTS `tbl_r_otp`;
CREATE TABLE `tbl_r_otp`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `phone_no` varchar(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `otp_code` varchar(6) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `expired_date` datetime(0) NULL DEFAULT NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for tbl_r_payment
-- ----------------------------
DROP TABLE IF EXISTS `tbl_r_payment`;
CREATE TABLE `tbl_r_payment`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `invoice_no` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `id_user` int(11) NULL DEFAULT NULL,
  `id_seller` int(255) NULL DEFAULT NULL,
  `id_payment` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `sender_name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `sender_bank` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `nominal` int(11) NULL DEFAULT NULL,
  `date_payment` date NULL DEFAULT NULL,
  `img_payment` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `stat_payment` int(11) NULL DEFAULT 0,
  `create_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_r_payment
-- ----------------------------
INSERT INTO `tbl_r_payment` VALUES (1, '125898565255', 1, NULL, NULL, 'Budi', 'Bank BCA', 100000, NULL, NULL, 0, '2019-07-05 08:49:16');
INSERT INTO `tbl_r_payment` VALUES (2, 'WTB20190811214322', 93, NULL, NULL, '1', '1', 1, NULL, NULL, 0, '2019-08-11 22:25:32');

-- ----------------------------
-- Table structure for tbl_r_req_off
-- ----------------------------
DROP TABLE IF EXISTS `tbl_r_req_off`;
CREATE TABLE `tbl_r_req_off`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `no_offers` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `type_order` enum('REQUEST','OFFERS') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `id_sender` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `id_receiver` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `date_send` datetime(0) NULL DEFAULT NULL,
  `price` int(11) NULL DEFAULT NULL,
  `downpayment` int(11) NULL DEFAULT NULL,
  `detail_sender` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `detail_receiver` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  `created_at` datetime(0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 6 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tbl_r_req_off
-- ----------------------------
INSERT INTO `tbl_r_req_off` VALUES (5, 'WTB20190811214322', 'OFFERS', '95', '93', '2019-08-11 21:43:22', 1, 1, '12', NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
